import { useEffect } from "react";
import Head from "next/head";
import { themeChange } from "theme-change";

export default function Home() {
  useEffect(() => {
    themeChange(false);
  }, []);

  return (
    <>
      <Head>
        <title>HAAMCHELIN</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>hello world</div>
        <button className="btn btn-primary">button</button>
      </main>
    </>
  );
}
